# ____________________________ USERS ____________________________
###
# create users
POST http://localhost:3000/users/register 
Content-Type: application/json

{
    "email": "testmailfour@mail.com",
    "password": "12345678",
    "confirmPassword": "12345678"
}

###
# activate account
PUT http://localhost:3000/users/activate/623b76c5744649db24ad7659
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjNiNzZjNTc0NDY0OWRiMjRhZDc2NTkiLCJyb2wiOmZhbHNlLCJpYXQiOjE2NDgwNjQxOTcsImV4cCI6MTY1MTY2NDE5N30.YnNX3-YZgT6HxQNjYv878zKy2S08J9lxqPwRmqe34Yk
Content-Type: application/json

###
# login
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "email": "testmailthree@mail.com",
    "password": "12345678"
}


###
# update user
PUT http://localhost:3000/users/623b6521f4ff389ef4c00566
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjNiNjUyMWY0ZmYzODllZjRjMDA1NjYiLCJyb2wiOmZhbHNlLCJpYXQiOjE2NDgwNTk2ODEsImV4cCI6MTY1MTY1OTY4MX0.w7AphfL4yloqbiBg8MJzp529uekhjxckj2BssrmeRx4
Content-Type: application/json

{
    "city": "Kołobrzeg"
}

###
# delete user
DELETE http://localhost:3000/users/623b6521f4ff389ef4c00566
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjNiNjUyMWY0ZmYzODllZjRjMDA1NjYiLCJyb2wiOmZhbHNlLCJpYXQiOjE2NDgwNTk2ODEsImV4cCI6MTY1MTY1OTY4MX0.w7AphfL4yloqbiBg8MJzp529uekhjxckj2BssrmeRx4
Content-Type: application/json


# ____________________________ CATEGORIES____________________________
###
# create category
POST http://localhost:3000/categories
Content-Type: application/json

{
	"name": "marchew"
}

###
# get all categories
GET http://localhost:3000/categories

###
# ____________________________ HEIGHTS____________________________
# create height
POST http://localhost:3000/heights
Content-Type: application/json

{
	"range": "123-123"
}

###
# get all heights
GET http://localhost:3000/heights

###
# ____________________________ OFFERS____________________________
# create offer
POST http://localhost:3000/offers
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjNiNzZjNTc0NDY0OWRiMjRhZDc2NTkiLCJyb2wiOmZhbHNlLCJpYXQiOjE2NDgwNjQxOTcsImV4cCI6MTY1MTY2NDE5N30.YnNX3-YZgT6HxQNjYv878zKy2S08J9lxqPwRmqe34Yk
Content-Type: application/json

{
    "userId": "623b64abf4ff389ef4c00562",
	"title": "Brukselka",
    "description": "Adoptuj brukselkę!",
    "city": "Lodówka",
    "phoneNumber": "989898982",
    "category": "623a4712db6477afcad4d52a",
    "height": "623a411ad32b3e7b591c0679",
    "price": 1330,
    "forExchange": false,
    "photos": []
}

###
# get all offers
GET http://localhost:3000/offers


###
# update offer
PUT http://localhost:3000/offers/623b775f744649db24ad765e
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjNiNzZjNTc0NDY0OWRiMjRhZDc2NTkiLCJyb2wiOmZhbHNlLCJpYXQiOjE2NDgwNjQxOTcsImV4cCI6MTY1MTY2NDE5N30.YnNX3-YZgT6HxQNjYv878zKy2S08J9lxqPwRmqe34Yk
Content-Type: application/json

{
    "userId": "623b64abf4ff389ef4c00562",
	"title": "Kalafior",
    "description": "Adoptuj kalafioraaa!",
    "city": "Las Canarias",
    "phoneNumber": "123234345",
    "category": "623a4712db6477afcad4d52a",
    "height": "623a411ad32b3e7b591c0679",
    "price": 1330,
    "forExchange": false,
    "photos": []
}